//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalInclusionApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalInclusionApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d609243a20117cb8132988815ded3c8b {
            get {
                object obj = ResourceManager.GetObject("d609243a20117cb8132988815ded3c8b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///  &quot;name&quot;: &quot;portuguese&quot;,
        ///  &quot;_comment&quot;: &quot;Sourced from: https://www.wordandphrase.info/port&quot;,
        ///
        ///  &quot;bcp47&quot;: &quot;pt-PT&quot;,
        ///  &quot;words&quot;: [
        ///    &quot;o&quot;,
        ///    &quot;de&quot;,
        ///    &quot;e&quot;,
        ///    &quot;em&quot;,
        ///    &quot;um&quot;,
        ///    &quot;que&quot;,
        ///    &quot;a&quot;,
        ///    &quot;ser&quot;,
        ///    &quot;para&quot;,
        ///    &quot;não&quot;,
        ///    &quot;com&quot;,
        ///    &quot;por&quot;,
        ///    &quot;ter&quot;,
        ///    &quot;se&quot;,
        ///    &quot;seu&quot;,
        ///    &quot;eu&quot;,
        ///    &quot;ele&quot;,
        ///    &quot;fazer&quot;,
        ///    &quot;mais&quot;,
        ///    &quot;este&quot;,
        ///    &quot;ou&quot;,
        ///    &quot;poder&quot;,
        ///    &quot;estar&quot;,
        ///    &quot;esse&quot;,
        ///    &quot;mas&quot;,
        ///    &quot;ir&quot;,
        ///    &quot;todo&quot;,
        ///    &quot;outro&quot;,
        ///    &quot;meu&quot;,
        ///    &quot;muito&quot;,
        ///    &quot;dizer&quot;,
        ///    &quot;ano&quot;,
        ///    &quot;isso&quot;,
        ///    &quot;ela&quot;,
        ///    &quot;t [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string portuguese {
            get {
                return ResourceManager.GetString("portuguese", resourceCulture);
            }
        }
    }
}
